Tr2 18
green-fox-academy/Rueppellii-Tribes-Backend2 pull request #17
Opened 2019-01-29 12:49 UTC by starlinginferno

GET Kingdom endpoint is done (it doesn't return with empty lists for now because that's only possible when we have troops, resources and buildings)

2019-01-29 12:54 UTC, aczender approved these changes

2019-01-29 12:58 UTC, giba86 approved these changes
Seems good, controller works.

2019-01-29 18:49 UTC, csadesz requested changes

2019-01-29 18:49 UTC, csadesz commented on src/main/java/rueppellii/backend2/tribes/kingdom/KingdomService.java
> +    public KingdomDTO getKingdomByUsername() throws KingdomNotValidException {
This method is a bit messy, think about a little how can you refactor that.😺

2019-01-29 18:49 UTC, csadesz commented on src/test/java/rueppellii/backend2/tribes/user/ApplicationUserServiceTest.java
> +//    @Test
commented tests 😮

2019-01-31 10:37 UTC, csadesz approved these changes

2019-01-31 10:52 UTC, merged