Tr2 15
green-fox-academy/Rueppellii-Tribes-Backend2 pull request #18
Opened 2019-01-29 16:22 UTC by aczender

2019-01-29 16:37 UTC, starlinginferno approved these changes
would prefer separate tables for the connection but good job!

2019-01-29 18:45 UTC, csadesz requested changes

2019-01-29 18:45 UTC, csadesz commented on src/main/java/rueppellii/backend2/tribes/resource/ResourceService.java
> +        } else throw new IllegalArgumentException();
else unneccessary

2019-01-29 18:45 UTC, csadesz commented on src/main/java/rueppellii/backend2/tribes/resource/ResourceService.java
> +
empty lines

2019-01-29 18:45 UTC, csadesz commented on src/test/java/rueppellii/backend2/tribes/resource/ResourceServiceTest.java
> +    private ResponseEntity r;
I think in some case "response" would be more readable than "r"

for example:

.... .isEqualTo(response);  (like a book 😄)

2019-01-29 18:45 UTC, csadesz commented on src/main/java/rueppellii/backend2/tribes/resource/Resource.java
> +    @JoinColumn(name = "kingdom_id", nullable = false)
prefer separate tables for the connection as Lili said :)

2019-01-31 10:37 UTC, csadesz approved these changes

2019-01-31 10:48 UTC, merged