Tr2 9 b
green-fox-academy/Rueppellii-Tribes-Backend2 pull request #25
Opened 2019-02-04 17:38 UTC by starlinginferno

TEST IS WORKING :D

2019-02-04 18:10 UTC, aczender approved these changes

2019-02-04 18:15 UTC, Ordash requested changes
Lili nem lesz jo hogy kiszedted azt hogy optionalt dob vissza a findbyusername mert akkor loginnal egy errort fogunk kapni ha nincs olyan username amit bekuldunk body-ba...

2019-02-04 19:30 UTC, starlinginferno commented
> 
> 
> Lili nem lesz jo hogy kiszedted azt hogy optionalt dob vissza a findbyusername mert akkor loginnal egy nagy budos errort fogunk kapni ha nincs olyan username amit bekuldunk body-ba...

Fixed ;)

2019-02-04 19:52 UTC, giba86 approved these changes
Seems good, I believe that it works as it should. :)

2019-02-05 10:11 UTC, csadesz approved these changes

2019-02-05 10:14 UTC, Ordash approved these changes

2019-02-05 10:15 UTC, merged