Tr2 55b
green-fox-academy/Rueppellii-Tribes-Backend2 pull request #70
Opened 2019-03-01 14:31 UTC by starlinginferno

TR2-55 and TR2-56 and everything that goes with them completed

- country codes are in a txt file in resources
- method to read and split them to get only the codes
- changed the registration so that it requires a country code besides the name, password and kingdom name
- validate location: must be on the list (CountryCodeNotValidException) and must not yet be in the repository (LocationAlreadyTakenException)
- location is in ManyToOne relationship with kingdom, has a service and repository
- two DTOs, one with one kingdom and another with kingdom list
- get endpoint gives back kingdom list with locations
- broke Archie's tests a little but fixed them! ;)

2019-03-02 17:13 UTC, giba86 commented
Look nice, I approve it

2019-03-04 09:55 UTC, giba86 approved these changes
stream look nince. Approve it

2019-03-05 09:02 UTC, csadesz requested changes

2019-03-05 09:02 UTC, csadesz commented on src/main/java/rueppellii/backend2/tribes/kingdom/service/KingdomService.java
> +    public Kingdom createNewKingdomAndSetNameIfNotExists(ApplicationUserDTO applicationUserDTO) throws IOException, CountryCodeNotValidException, LocationIsTakenException {
refactor this method, if the method's name contains "and", it doesn't sound great :) Talk about it

2019-03-06 11:50 UTC, csadesz approved these changes

2019-03-08 09:50 UTC, merged