Tr2 69
green-fox-academy/Rueppellii-Tribes-Backend2 pull request #72
Opened 2019-03-02 20:20 UTC by giba86

1 Flyway schema simplified
2 TroopService integration test added. all functions except getKingdomTroops and getTroopsWithTheGivenLevel as these are used by  validateUpgradeTroopRequest
3 validateUpgradeTroopRequest tested for exceptions and all levels (1, 2, 3)

2019-03-04 06:08 UTC, aczender approved these changes
Tests are running smoothly

2019-03-04 09:36 UTC, Ordash approved these changes

2019-03-04 09:56 UTC, starlinginferno approved these changes

2019-03-05 08:59 UTC, csadesz requested changes

2019-03-05 08:59 UTC, csadesz commented on src/test/java/rueppellii/backend2/tribes/troop/TroopServiceTest.java
> +package rueppellii.backend2.tribes.troop;
Talk about: 

- test naming
- variables usage
- PR content

2019-03-06 11:51 UTC, csadesz approved these changes

2019-03-08 09:36 UTC, merged